boutique_calendrier:
    resource: "@BoutiqueCalendrierBundle/Resources/config/routing.yml"
    prefix:   /

boutique_user:
    resource: "@BoutiqueUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

 