<?php

namespace Boutique\CalendrierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalariesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalariesRepository extends EntityRepository
{
}
