boutique_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: BoutiqueUserBundle:Default:index }

 
login:
    pattern:   /login
    defaults:  { _controller: BoutiqueUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout