parameters:
#    boutique_user.example.class: Boutique\UserBundle\Example

services:
#    boutique_user.example:
#        class: %boutique_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
